services:
  app:
    container_name: app
    build: .
    ports:
      - '8022:22'
      - '8080:8080'
      - '8443:8443'
    # https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html#environment-variables
    environment:
      - SSH_PUBLIC_KEY
      # To debug sshd:
      #- SERVICE_SSH_OPTS=-d
    volumes:
      - 'app-data:/app/'
      #- 'ssh-config-data:/etc/ssh/'
    networks:
      - default
    restart: unless-stopped
    stdin_open: true
    tty: true

  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - 'mysql-data:/var/lib/mysql/'
    networks:
      - default
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  app-data:
    driver: local
  ssh-config-data:
    driver: local
  mysql-data:
    driver: local
