services:
  app:
    container_name: app
    build: .
    ports:
      - '8022:22'
      - '8080:80'
      - '8443:443'
    # https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html#environment-variables
    environment:
      - USE_PUBLIC_KEY
      - SSH_PUBLIC_KEY
      - SSH_PASSWORD
      - WEB_DOCUMENT_ROOT=/app/current/public
      # To debug sshd:
      #- SERVICE_SSH_OPTS=-d
    volumes:
      - 'app-data:/app/'
      # Persist host keys:
      - 'ssh-config-data:/etc/ssh/'
      - '/etc/timezone:/etc/timezone:ro'
    networks:
      - default
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    stdin_open: true
    tty: true

  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - 'mysql-data:/var/lib/mysql/'
      - '/etc/timezone:/etc/timezone:ro'
    networks:
      - default
    restart: unless-stopped
    stdin_open: true
    tty: true

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - 'redis-data:/data/'
      - '/etc/timezone:/etc/timezone:ro'
    networks:
      - default
    # command: redis-server --save 20 1 --loglevel warning --requirepass $PASSWORD
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  app-data:
    driver: local
  ssh-config-data:
    driver: local
  mysql-data:
    driver: local
  redis-data:
    driver: local
