name: Static Analysis
on:
  push:
    branches:
      - master
  workflow_call: # Make this workflow callable from other workflows
  workflow_dispatch: # Make this workflow runnable on github

jobs:
  analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare App
        uses: michiruf/laravel-ci/prepare-app@main
        with:
          php-version: '8.4'
          php-additional-extensions: 'imap'

      - name: Run Static Analysis
        run: ./vendor/bin/phpstan --no-progress --error-format=github
