# see https://github.com/marketplace/actions/laravel-deploy

name: Deploy
on:
  push:
    tags:
      - '*'
  # Make this workflow callable from other workflows
  workflow_call:
  # Make this workflow runnable on github
  workflow_run:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare App
        uses: ./.github/workflows/prepare-app

      - name: Run Tests
        uses: ./.github/workflows/run-tests.yml

      - name: Run Analysis
        uses: ./.github/workflows/analysis.yml

#      - name: Deploy to Server
#        uses: ngocquyhoang/deploy@laravel
#        with:
#          host: host
#          user: user
#          port: port
#          path: path
#          owner: owner
#        env:
#          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - run: echo 'Hello from deployment'
