# see https://github.com/marketplace/actions/laravel-deploy

name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Prepare App
#        uses: ./.github/workflows/prepare-app
#
#      - name: Deploy to Server
#        uses: ngocquyhoang/deploy@laravel
#        with:
#          host: host
#          user: user
#          port: port
#          path: path
#          owner: owner
#        env:
#          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
