# see https://github.com/marketplace/actions/laravel-deploy

name: Deploy
on:
  push:
    tags:
      - '*'
  workflow_call: # Make this workflow callable from other workflows
  workflow_dispatch: # Make this workflow runnable on github

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
  analysis:
    uses: ./.github/workflows/analysis.yml
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - test
      - analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare App
        uses: ./.github/workflows/prepare-app

      # TODO Maybe use deployer?
      #      https://deployer.org/docs/7.x/recipe/laravel
#      - name: Deploy to Server
#        uses: ngocquyhoang/deploy@laravel
#        with:
#          host: host
#          user: user
#          port: port
#          path: path
#          owner: owner
#        env:
#          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - run: echo 'Hello from deployment'
