name: Publish Docker Images

on:
  push:
    tags:
      - '*'
  workflow_call: # Make this workflow callable from other workflows
  workflow_dispatch: # Make this workflow runnable on github

env:
  REGISTRY: ghcr.io

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs:
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Base Image
        uses: ./.github/workflows/publish-docker-image
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ github.repository_owner }}/laravel
          tag: base
          build-context: _docker

  build-variants:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs:
      - build-base
    strategy:
      matrix:
        variant:
          - name: autopull
            image-scope: laravel
            additional-contexts:
          - name: baked
            image-scope: catchall-subdirectories
            additional-contexts: src_root=.
          - name: deployer
            image-scope: laravel
            additional-contexts:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare App for Tests
        uses: ./.github/workflows/prepare-app

      - name: Install sshpass for Tests
        if: ${{ matrix.variant.name == 'deployer' }}
        run: sudo apt-get install sshpass

      - name: Run Tests for Variant '${{ matrix.variant.name }}'
        run: php artisan test --group=${{ matrix.variant.name }} -v

      - name: Alias Base Image Tag
        run: |
          docker pull ${{ env.REGISTRY }}/${{ github.repository_owner }}/laravel:base-latest
          docker image tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/laravel:base-latest base

      - name: Publish Image Variant '${{ matrix.variant.name }}'
        uses: ./.github/workflows/publish-docker-image
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ github.repository_owner }}/${{ matrix.variant.image-scope }}
          tag: ${{ matrix.variant.name }}
          build-context: _docker/${{ matrix.variant.name }}
          additional-contexts: ${{ matrix.variant.additional-contexts }}
