name: Run Tests
on:
  push:
    branches:
      - main
      - ci
  # Make this workflow callable from other workflows
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare App
        uses: ./.github/workflows/prepare-app

      - name: Run Tests
        run: php artisan test --exclude-group=long-running,wip -v
