name: Run Tests
on:
  push:
    tags:
      - '*'
    branches:
      - main
      - ci

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Prepare App
        uses: ./.github/workflows/prepare-app

      - name: Run Tests
        run: php artisan test --exclude-group=long-running,wip -v
