name: Run Tests
on:
  push:
  workflow_call: # Make this workflow callable from other workflows
  workflow_dispatch: # Make this workflow runnable on github

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare App
        uses: michiruf/laravel-ci/prepare-app@main
        with:
          coverage: ${{ inputs.coverage == 'true' && 'pcov' || 'none' }}
          php-version: '8.4'
          php-additional-extensions: 'imap'

      - name: Run Tests
        run: php artisan test --filter=PrintDirectorySummaryCommandTest -v
